/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg304ui.UI;

import facadeUI.LogInManager;
import facadeUI.UserManager;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import pkg304ui.UIUpdater;

/**
 *
 * @author Daniel Lê
 */
public class UIFrame extends javax.swing.JFrame {

    /**
     * Creates new form UIMain
     */
    public UIFrame() {
        initComponents();
        LogoutButton.setEnabled(false);
        getMessagesButton.setEnabled(false);
        sendMessageButton.setEnabled(false);
        sendMessageTextField.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LeftPanel = new javax.swing.JPanel();
        PickUserButton = new javax.swing.JButton();
        currentUserStaticLabel = new javax.swing.JLabel();
        currentUserDynamicLabel = new javax.swing.JLabel();
        matchesDropdown = new javax.swing.JComboBox<>();
        matchesStaticLabel = new javax.swing.JLabel();
        errorDynamicLabel = new javax.swing.JLabel();
        LogoutButton = new javax.swing.JButton();
        getMessagesButton = new javax.swing.JButton();
        sendMessageButton = new javax.swing.JButton();
        sendMessageTextField = new javax.swing.JTextField();
        RightPanel = new javax.swing.JPanel();
        RightScroll = new javax.swing.JScrollPane();
        RightText = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("UIFrame"); // NOI18N
        setResizable(false);

        LeftPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LeftPanel.setPreferredSize(new java.awt.Dimension(489, 744));

        PickUserButton.setText("Pick User");
        PickUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PickUserButtonActionPerformed(evt);
            }
        });

        currentUserStaticLabel.setText("Current User: ");

        matchesStaticLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        matchesStaticLabel.setText("Matches");

        errorDynamicLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        errorDynamicLabel.setForeground(new java.awt.Color(222, 0, 0));

        LogoutButton.setText("Logout");
        LogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });

        getMessagesButton.setText("Get Messages");
        getMessagesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getMessagesButtonActionPerformed(evt);
            }
        });

        sendMessageButton.setText("Send Message");
        sendMessageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendMessageButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LeftPanelLayout = new javax.swing.GroupLayout(LeftPanel);
        LeftPanel.setLayout(LeftPanelLayout);
        LeftPanelLayout.setHorizontalGroup(
            LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LeftPanelLayout.createSequentialGroup()
                        .addGroup(LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(errorDynamicLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(LeftPanelLayout.createSequentialGroup()
                                .addComponent(PickUserButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(currentUserStaticLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(currentUserDynamicLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE))
                            .addGroup(LeftPanelLayout.createSequentialGroup()
                                .addComponent(matchesStaticLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(matchesDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(16, 16, 16)
                        .addComponent(LogoutButton))
                    .addGroup(LeftPanelLayout.createSequentialGroup()
                        .addGroup(LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(getMessagesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sendMessageButton, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sendMessageTextField)))
                .addContainerGap())
        );
        LeftPanelLayout.setVerticalGroup(
            LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PickUserButton)
                    .addComponent(currentUserStaticLabel)
                    .addComponent(currentUserDynamicLabel)
                    .addComponent(LogoutButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(matchesStaticLabel)
                    .addComponent(matchesDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(getMessagesButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sendMessageButton)
                    .addComponent(sendMessageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 601, Short.MAX_VALUE)
                .addComponent(errorDynamicLabel)
                .addContainerGap())
        );

        RightPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        RightPanel.setPreferredSize(new java.awt.Dimension(489, 744));

        RightScroll.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        RightText.setEditable(false);
        RightScroll.setViewportView(RightText);

        javax.swing.GroupLayout RightPanelLayout = new javax.swing.GroupLayout(RightPanel);
        RightPanel.setLayout(RightPanelLayout);
        RightPanelLayout.setHorizontalGroup(
            RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RightScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        RightPanelLayout.setVerticalGroup(
            RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RightScroll)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LeftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(RightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LeftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        LeftPanel.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PickUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PickUserButtonActionPerformed
        String userEmail = JOptionPane.showInputDialog("Please enter a user email");
        if (userEmail == null) {
            return;
        }
        LogInManager logInManager = LogInManager.getInstance();
        logInManager.login(userEmail);
        if (logInManager.isLoggedOn()) {
            LogoutButton.setEnabled(true);
            getMessagesButton.setEnabled(true);
            sendMessageButton.setEnabled(true);
            sendMessageTextField.setEnabled(true);
        } else {
            int createNew = JOptionPane.showConfirmDialog(null, "This user doesn't exist. Do you want to create an account for this user?");
            if (createNew == JOptionPane.YES_OPTION) {
                String userName = JOptionPane.showInputDialog("Please enter a name for this user.");
                logInManager.signUp(userEmail, userName);
                LogoutButton.setEnabled(true);
                getMessagesButton.setEnabled(true);
                sendMessageButton.setEnabled(true);
                sendMessageTextField.setEnabled(true);
            } else {
                return;
            }
        }
        List matches = new ArrayList();
        UserManager userManager = UserManager.getInstance();
        userManager.getMatch(); // TODO - get result from midlayer
        UIUpdater.login(userEmail, matches);
    }//GEN-LAST:event_PickUserButtonActionPerformed

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
        LogInManager logInManager = LogInManager.getInstance();
        if (logInManager.isLoggedOn()) {
            logInManager.logout();
            LogoutButton.setEnabled(false);
            getMessagesButton.setEnabled(false);
            sendMessageButton.setEnabled(false);
            sendMessageTextField.setEnabled(false);
        } else {
            UIUpdater.error("Cannot log out. Not logged in.");
        }
    }//GEN-LAST:event_LogoutButtonActionPerformed

    private void getMessagesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getMessagesButtonActionPerformed
        LogInManager logInManager = LogInManager.getInstance();
        UserManager userManager = UserManager.getInstance();
        if (logInManager.isLoggedOn()) {
            if (matchesDropdown.getSelectedItem() != null) {
                String otherUser = (String)matchesDropdown.getSelectedItem();
                userManager.getMessage(otherUser);
                List messages = new ArrayList();
                UIUpdater.getMessages(messages);
            } else {
                UIUpdater.error("No user selected.");
            }
        } else {
            UIUpdater.error("Not logged in.");
        }
    }//GEN-LAST:event_getMessagesButtonActionPerformed

    private void sendMessageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendMessageButtonActionPerformed
        LogInManager logInManager = LogInManager.getInstance();
        UserManager userManager = UserManager.getInstance();
        if (logInManager.isLoggedOn()) {
            if (matchesDropdown.getSelectedItem() != null) {
                String otherUser = (String) matchesDropdown.getSelectedItem();
                String message = sendMessageTextField.getText();
                userManager.sendMessage(otherUser, message);
                UIUpdater.setText("Message sent to " + otherUser + ": " + message);
            } else {
                UIUpdater.error("No user selected.");
            }
        } else {
            UIUpdater.error("Not logged in.");
        }
    }//GEN-LAST:event_sendMessageButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UIFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel LeftPanel;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JButton PickUserButton;
    private javax.swing.JPanel RightPanel;
    private javax.swing.JScrollPane RightScroll;
    public javax.swing.JTextPane RightText;
    public javax.swing.JLabel currentUserDynamicLabel;
    private javax.swing.JLabel currentUserStaticLabel;
    public javax.swing.JLabel errorDynamicLabel;
    private javax.swing.JButton getMessagesButton;
    public javax.swing.JComboBox<String> matchesDropdown;
    private javax.swing.JLabel matchesStaticLabel;
    private javax.swing.JButton sendMessageButton;
    private javax.swing.JTextField sendMessageTextField;
    // End of variables declaration//GEN-END:variables
}
